### ISSUE TITLE
Error on raspberry pi

### ISSUE THREAD

**Issue by charlyhue** [benjaminjonard/koillection#273]
Hello,

On raspberry pi 3 I got this error on admin page
Argument 1 passed to App\Twig\AppRuntime::bytes() must be of the type int, float given, called in /var/www/koillection/var/cache/dev/twig/c7/c7b5c01be9a3f03cfb233d9288b4c116a6aee68c0eb7ea1b0521db978a7e512c.php on line 163

If I change public function bytes(int $bytes, int $precision = 2) : string to public function bytes(float $bytes, int $precision = 2) : string in src/Twig/AppRuntime.php there is no more errors.

**Comment by benjaminjonard** [comment]
Hello, 

Thanks for reporting and investigating this bug, I just published the fix. 
I'm planning to do a new release today or tomorrow (still need to do some tests)

**Comment by benjaminjonard** [comment]
Hello,
The bug should be fixed on version 1.1.6

**Comment by charlyhue** [comment]
Hello,
Yes the bug is fixed
Thanks!
