### ISSUE TITLE
Shared Templates

### ISSUE THREAD

**Issue by Zwordi** [benjaminjonard/koillection#311]
Hi,

Just installed it and i love it.
I was just wondering if some templates could come directly with the setup like DVD/Manga/BD etc.
In the website, there is pictures with full detailed manga with ISBN etc, are those grabbed from public IP or it is full manually entries ?

Thanks you for this project, i was looking for something like that and i had only found https://github.com/curiositry/ReaDB.

Zwordi

**Comment by benjaminjonard** [comment]
Hello,

Thanks for your interest in this project, it's nice to have some feedback :slightly_smiling_face: 

The templates are manually created. I did give some thought about adding some default templates, but as the aim of this project is to be fit for every types of collections I chose not to (someone who would use it for a collection of old coins wouldn't really care about having a DVD prebuilt template)

**Comment by Zwordi** [comment]
Hi Benjamin,

I understand your point, would it be possible to have on a docs at least an example because actually i don’t know really how to start my template. Which field to add etc.

Are you planning to add some docs ? Would you accept merge request with markdown example (docker + traefik + letsencrypt ssl) on my case :). 

Have a nice week-end,

Zwordi

**Comment by benjaminjonard** [comment]
Hi, 

The template feature is one of the oldest feature of the project and I agree it may need a revamp to be easier to understand. The fields types are pretty generic :
- Text :  any kind of text (title, author, ISBN...)
- Country :  select list of countries
- Date:  any kind of date (release date...)
- Rating : a 5 stars rating system (will be shipped with 1.2)
- Image: any kind of image (back cover, a photo...)
- Sign: a special type of image for autographs, artist signature on a book, a CD... (the only difference with other images is that they will also appear on a special menu on the left menu)
- File: any kind of file (could be a PDF version of a book for example)

I will add some field types if the need arise (I'll probably add a 'number' field for example in the very near future)
[Click here to see a Book template I use](https://user-images.githubusercontent.com/20560781/112755631-c9252380-8fe1-11eb-849e-afbd6bd1a277.png)

I'm also using Traefik and Letsencrypt, so yes it would be nice to have an example for a full production ready setup.  I would gladly merge it :slightly_smiling_face: 

Thanks

**Comment by benjaminjonard** [comment]
Hello @Zwordi thanks for your PR, I can add you to the contributors list if you wish so

**Comment by Zwordi** [comment]
That’s fine for me, thank you. I’m closing the issue.
