### ISSUE TITLE
REST-ish API?

### ISSUE THREAD

**Issue by nogarcia** [benjaminjonard/koillection#351]
I've just started using Koillection this weekend, and I'm really enjoying the experience! However, adding each item of my collection by hand is beginning to get tedious. 

Being able to write a script to scrape the metadata of my collection from sources online would make it much faster. Is there any way (or a possibility of there being one in the future) to programmatically add items to collections? Symfony forms seem to simply accept POST requests, but this token parameter has gotten in my way.
![image](https://user-images.githubusercontent.com/37482938/132137417-3808b7b6-7e7e-4cdd-87e2-34cfdd4b1ed7.png)

**Comment by benjaminjonard** [comment]
Hello,

There is no way right now to programmatically add items. I was thinking of adding a REST API but it will require some work I can't do right now.

The token is here for security purpose (against CSRF attacks). If the only problem for you is this token, I can add a new URL that will behave exactly the same as the form but without the token.

**Comment by nogarcia** [comment]
If it's an inconvenience, then don't worry about it! There's no need to sacrifice security for convenience.

On the topic of the CSRF token, I hadn't been able to find the token in any of the form templates, but recently I found the element in the rendered output. Using this, I've had mild success in querying items using my login. Soon, I'll be able to add items using a Python script. 

I'll post my script in this issue via Gist when I'm done. 

Thank you for your response!

**Comment by nogarcia** [comment]
I've now used a small script to add my entire collection in a matter of seconds! My code's nowhere near clean and may need to be rewritten in order to function for *all* setups, but it's a workable demo of getting a login working and mocking an addition to a collection. I haven't implemented it, but you could also send deletes and edits using the same session. Gist [here](https://gist.github.com/radiohazard-dev/2f8ea1c4b457bec1ea44a8b4b6aa9c6b).

I considered writing a cleaner API for a Koillection module, but I decided that, with the current approach, it'd be a little hacky.

**Comment by benjaminjonard** [comment]
Nice, I'll have a closer look later.

I'm looking at the possibility to add a proper REST API but it will take some time. I still have to see how to best handle authentication and file uploads.

**Comment by Zwordi** [comment]
Guys,

Thanks to both of you :).
I will try to find time to also use this script to have my collections exported.
I’m using mangasanctuary but it doesn’t provide data for other types of books or collection.

Will keep you posted !

Thanks @benjaminjonard  for your recent work. 

Thanks,

**Comment by benjaminjonard** [comment]
Closing the issue, a REST API is now available
