### ISSUE TITLE
Failed to create symbolic link

### ISSUE THREAD

**Issue by lopiv2** [benjaminjonard/koillection#352]
When installed trough Docker, and sometime after the container is deployed, i receive the next error in log:

**** Copy the .env to /conf ****,
**** Make sure the /conf and /uploads folders exist ****,
**** Create the symbolic link for the /uploads folder ****,
ln: failed to create symbolic link '/var/www/koillection/.env.local': File exists

Those folders already exist.

The only way to get rid of this error is recreating the container again.

**Comment by benjaminjonard** [comment]
Hello, I've updated the Docker image.

If you pull the new version with `docker-compose pull`, it should fix this issue
