### ISSUE TITLE
Docker container takes 15 mins to start

### ISSUE THREAD

**Issue by daknin** [benjaminjonard/koillection#366]
The koillection container takes about 15 mins to start on one of my servers, caused by this command:  `chown -R www-data:www-data /var/www/koillection` in `entrypoint.sh`

The root cause is probably https://github.com/docker/for-linux/issues/388. Until that is fixed I wondered if there is anything you can do. 

The problem server is running Docker on Ubuntu 20.04 using Hyper-V VM, startup takes only a few seconds on different server so it's definitely not a general issue.

**Comment by benjaminjonard** [comment]
Hello, the last release should have fixed this issue. Please do tell me if you still encounter this problem after updating.

**Comment by daknin** [comment]
I've tried the latest release and it fixes the issue. Thanks
