### ISSUE TITLE
System crashes when adding gifs as the collection image

### ISSUE THREAD

**Issue by ItsNoted** [benjaminjonard/koillection#401]
When I add a gif as an image for the collection cover the app crashes when I press submit.

https://snip.lol/JipE3/RiWidELu53.png

**Comment by benjaminjonard** [comment]
Hello, 

I couldn't reproduce, could you please provide me some logs ? They should be located in `var/log/prod.log` from the project root directory.
Right now thought, the collection cover doesn't support animated images, you'll only get a static image (the first frame of the gif). 
I think I have an idea how to handle it, I'll try a bit later.
