### ISSUE TITLE
[Feature Request] Links for template field type

### ISSUE THREAD

**Issue by ItsNoted** [benjaminjonard/koillection#402]
Can you implement links as a template field type so we can link to external sources? This would be especially useful for those who collect digital assets.

https://snip.lol/JipE3/ZUQIBuKa71.png

Thanks!

**Comment by benjaminjonard** [comment]
Seems like a good idea, I'll add it to the next release that should come this week.

Thanks

**Comment by benjaminjonard** [comment]
Hello, the last release (1.3.3) now includes the new Link type
