### ISSUE TITLE
Issue with Docker install and Templates/File fields

### ISSUE THREAD

**Issue by gsargent70** [benjaminjonard/koillection#403]
Every time I create an item and use a template to add fields or create an item with a file field I get this error each time I try to open it

Oops, a critical error occured :(

Is there any logging anywhere that can help me figure out what the error is?

**Comment by benjaminjonard** [comment]
Hello, you can find logs in `var/log/prod.log` from the project root.

Using docker-compose it would be something like that : `docker-compose exec koillection tail -f var/log/prod.log`

**Comment by gsargent70** [comment]
ok thank you for that.  I see what the issue was.  That lead to another question and maybe I just don't know what the purpose of this field is for. 

So here is the situation.  I have digital assets that I would like to create a catalog for and be able to download that asset to whatever machine I am on when searching in the catalog.  I assumed that is what the field type of file was for.  The issue I am having is that when I insert the field type of file it gives me a button to create the link to the asset.  when I click on the button it gives me the file browser but it is for the local filesystem I am accessing the site from not the filesystem of the server itself.  So whatever links I create can only be for files that are local to the machine I am on.  Is there a way to enter the path directly in the field type of file rather than using the button to launch the file browser?

**Comment by benjaminjonard** [comment]
Yes, the file type is for uploading files from the local filesystem. 
Someone came up with something similar to your need a few days ago https://github.com/koillection/koillection/issues/402 
Would that be a solution for your problem ?

**Comment by gsargent70** [comment]
Yes I believe that would work.  I don't believe that is implemented yet though correct?

**Comment by benjaminjonard** [comment]
The code is done, I just need to test a few things. I will make a new release during the week

**Comment by benjaminjonard** [comment]
Hello, the last release (1.3.3) now includes the new Link type
