### ISSUE TITLE
Add tag missing in web

### ISSUE THREAD

**Issue by dvsqrd** [benjaminjonard/koillection#405]
Running koillection 1.3.3 with pgsql 14.2 on docker using official images. Launched with compose file.

It works fine, however there's no button to add a new tag. I can add tag categories though. Adding /add to the URL like with collections or wishlist gives HTTP error 404.

I was able to add a tag with the api and I can see this on web and assign the tag to items too.

**Comment by benjaminjonard** [comment]
Hello, could you check this comment and tell me if it works for you ? https://github.com/koillection/koillection/issues/378#issuecomment-1006926970

Thanks

**Comment by dvsqrd** [comment]
Oh that's how it works! Yeah it's working then.
