### ISSUE TITLE
Error 500 when item object contains an empty "File" or "Country" attribute

### ISSUE THREAD

**Issue by mcfisch** [benjaminjonard/koillection#419]
When an item contains empty data fields of the types "File" or "Country", trying to pick it from the collection results in an error 500. Manually adding "/edit" to the URL allows for editing the respective item and then it gets displayed properly again.

I noticed this first when creating a template with a dozen fields, and when I applied it to an item but let one of the "File" fields unpopulated the issue appeared. Once I found out what it caused I verified that it happens only to these 2 types.

Steps to reproduce:

1. Create or edit an item in a collection
2. Add a "File" or "Country" field without entering a value (resp. picking a file)
3. Click "Submit"
4. In case of a new item you'll then have to click on its avatar in the collection to trigger the error, while editing leads to the error immediately

**Comment by mcfisch** [comment]
BTW, I tried both version of the Docker image, stable and beta.

**Comment by benjaminjonard** [comment]
Hello, thanks for pointing that out, the fix will be in the next release

**Comment by Izanagi52** [comment]
Hello, I have the same issue, with the latest version (ARM64, 1.3.6, docker).
It's it normal ?
