### ISSUE TITLE
[Feature Request] Displaying item names in a collection

### ISSUE THREAD

**Issue by mcfisch** [benjaminjonard/koillection#420]
As far as I can tell so far the collection view never shows the names of the items, only the avatars/thumbnails. When using this software for something that's not focused on things like game titles, magazines, or other collectibles focused on visuals this isn't very helpful - I can't tell items apart unless I upload a picture for them. 

My use case is this:  I'm trying to track my woodworking workshop inventory/assets, which means a lot of tools, materials, and other items, but not all of them necessarily have a picture. And even if they would, this would not always make them easier to distinguish.

Maybe there could be an option in the settings to enable/disable the display of item names in collections?

Thanks

**Comment by benjaminjonard** [comment]
I've been thinking about this for a while now. But maybe a list view would be more appropriate for this kind of use case ? 
Especially if there is no thumbnails, the default ones take up quite some space for nothing

**Comment by mcfisch** [comment]
Sure, a clean list view would also be useful, especially if it contains multiple columns to display other fields, maybe even with the option to sort and filter.

However, a general option to enable the display of labels would be nice, too.

**Comment by Typhonragewind** [comment]
I fully support this, list view (especially if set per collection) would be an incredible feature

**Comment by benjaminjonard** [comment]
A new list view is available since last release (1.3.5)

**Comment by Typhonragewind** [comment]
You're amazing!
