### ISSUE TITLE
[Feature Request] Adding maintainable lists and a "List" field type to assign them to templates

### ISSUE THREAD

**Issue by mcfisch** [benjaminjonard/koillection#421]
As I mentioned in another issue I try to build a digital inventory for tracking my woodworking assets: tools, materials, consumables, workpieces, etc.

One helpful feature I'm missing in this otherwise very appealing software is this: a field of a type "List", that I can assign to a template, and which then gets assigned an actual list that has a bunch of entries. Basically, this is about adding user-defined (one-dimensional) arrays, that can be assigned to templates (or items directly), and is then providing the content of the respective array to the item that is created/edited.

Example

Let's say I have an item "Table saw", that already has the following attributes by default:
- Name
- Collection
- Quantity
- Visibility
- Tags

Now I apply a template that also adds these fields:
- Model (Text)
- Manufacturer (List)
- Supplier (List)
- Receipt (File)
- Manual (File)
- Supplier Link (Link)
- Purchase Date (Date)

The values for the two attributes "Manufacturer" and "Supplier" I would like to pick from lists, that are created similarly as templates. A link in the menu "Lists", and then lists of different manufacturers, of suppliers, or one that just has "Corded" and "Cordless" in it.

Whenever I add a "List" to an item it should ask which list and then provide the content as a pull-down for the value field in the form.

Does that make sense so far?

Thanks in advance!

**Comment by benjaminjonard** [comment]
Hello, this feature is now available since version 1.3.7
