### ISSUE TITLE
[Feature Request] Sort items by fields

### ISSUE THREAD

**Issue by absamue** [benjaminjonard/koillection#428]
I am using this project to track my personal reviews of games and shows. It would be useful to be able to sort the items in a collection by the item fields, such as sorting by Score or date fields.

**Comment by benjaminjonard** [comment]
Hello, I've made a first version for this feature that will be available in next release (still needs some tests).

**Comment by benjaminjonard** [comment]
Sorting on item name and data of types Date, Number and Rating are available since last release.

**Comment by batu-one** [comment]
What steps should I take to view this feature in action? I can't seem to find anything regarding sorting while viewing a collection.

**Comment by batu-one** [comment]
I found it, it's in the item settings while editing the collection.

**Comment by absamue** [comment]
Works great, tested with all the available data types. Thank you for your quick work on this @benjaminjonard
