### ISSUE TITLE
English Translation Bugs/Fixes

### ISSUE THREAD

**Issue by CorneliousJD** [benjaminjonard/koillection#434]
Some (very minor) fixes for the English translation would be

Sings > Signatures
Infos > Info
Wishlist "Comment" is correct on edit page, but the column name on Wishlist itself shows "name" again a 2nd time. 

A more major would would be the price column in wish list.
Where right now it shows 59.99 $ but in USA the proper format is $59.99

**Comment by benjaminjonard** [comment]
Thanks for your feedback, all these fixes will be available in next release
