### ISSUE TITLE
Feature Request - Pre-populate a template for all collection items. 

### ISSUE THREAD

**Issue by CorneliousJD** [benjaminjonard/koillection#436]
It would be very handy to have a feature where all items contained in a collection could be pre-populated with a template of your choosing.

For example, I plan to use Koillection to track a video game collection and I'd like every single item in the collection to show fields for progress, items owned (cartridge/box/manual/etc) and cosmetic condition, rating, etc.

Having to apply the template to each item we add is just a bit of a slow process, the option to have it pre populate all new items being added would be excellent.

This is a hard feature to describe in words, if there's any question about this please let me know.

**Comment by benjaminjonard** [comment]
This feature is available in the latest release
