### ISSUE TITLE
Feature Request - Collection List View

### ISSUE THREAD

**Issue by CorneliousJD** [benjaminjonard/koillection#437]
Right now list view can only be applied to actual collections themselves, so their ITEMS are in list view.

I would like the option to also show my collections themselves in a list view as well.

Very low priority, it would just be a "nice to have" option for those people who have long collection names and don't have a good image to represent it. 

PS - Sorry for all the feature requests, just had some ideas that I thought would be good to share!

**Comment by benjaminjonard** [comment]
Hello, list view for collections is now available (since release 1.3.14)
