### ISSUE TITLE
Doesn't handle rotation metadata in images

### ISSUE THREAD

**Issue by sanmadjack** [benjaminjonard/koillection#440]
Images with rotation metadata display correctly when opened, but the thumbnails generated don't take the rotation metadata into account. I've uploaded such an image here: https://drive.google.com/file/d/1tUx9aSKaPl2pSDW29EEha2ztx7WrNDk4/view?usp=sharing

**Comment by benjaminjonard** [comment]
This is a duplicate of #432, but thanks for sharing your image it helped me fixing the issue. 
This will be resolved in next release (you'll have to upload your image again though)

**Comment by sanmadjack** [comment]
No problem, thanks for fixing it so promptly. Do you have an estimate for when it will be released?

**Comment by benjaminjonard** [comment]
Probably on Wednesday, I need to properly test some new features

**Comment by benjaminjonard** [comment]
This issue should be fixed in release 1.3.6
