### ISSUE TITLE
Allow further zoom outs of icons

### ISSUE THREAD

**Issue by CorneliousJD** [benjaminjonard/koillection#441]
See screenshot below for an example. I have this icon I would like to upload as a collection thumbnail, but I'd like to zoom out far enough so that the entire icon is visible, but it doesn't let me keep zooming out.

it would be nice if we could keep zooming out to fit the entirety of an icon in the cropped circle shown.

![image](https://user-images.githubusercontent.com/724777/179432079-dc0f402a-c11c-4204-be0b-cd4cde4f5040.png)

**Comment by benjaminjonard** [comment]
I can allow infinite zoom out but it causes weird behaviors (I would only work properly if the image background is transparent)

![Screenshot 2022-07-18 at 16-59-02 Koillection](https://user-images.githubusercontent.com/20560781/179540777-5354f8a5-a211-4d01-a853-1c2eb0c66c06.png)

![Screenshot 2022-07-18 at 16-57-29 Koillection](https://user-images.githubusercontent.com/20560781/179540801-912d981e-59cb-4935-add6-d7587d23bc88.png)

I don't see a good solution for this. I had this issue myself, I solved that by copy-pasting the image on a wider background with an image editor

**Comment by CorneliousJD** [comment]
> I can allow infinite zoom out but it causes weird behaviors (I would only work properly if the image background is transparent)
> 
> I solved that by copy-pasting the image on a wider background with an image editor

This is a good enough solution for me - thanks! 
I'll just paste it into a bigger background and zoom in to crop from there :)
