### ISSUE TITLE
Feature Request - Checkboxes/Dropdowns

### ISSUE THREAD

**Issue by CorneliousJD** [benjaminjonard/koillection#446]
First off, I want to say a huge THANK YOU for implementing feature requests I have submitted thus far, this is an amazing tool, and continues to improve.

I was wondering if it would be possible to have metadata fields such as chekboxes, radio buttons, and/or dropdowns?

I am using Koillection to track a video game collection currently, and my thought process is as follows.

Checkbox: I could have a checkbox for for each component of the game I own, such as "cartridge, box, manual, extras"

Radio Buttons: I could use this as a progression tracker. "Unplayed, in progress, abandoned, beaten, completed" 

Dropdown: This could work instead of radio buttons? Not sure which is easier to implement, but both would serve the same purpose.

**Comment by benjaminjonard** [comment]
If I understand correctly this is a similar feature as #421, the idea would be to be able to create custom metadata types, like a "Game progress" list ?

**Comment by CorneliousJD** [comment]
Yes the list request in that would match the dropdown list I'm mentioning here. 

Checkboxes/radio buttons would also be a nice choice but Dropdown list would be the most versatile and flexible I suppose!
