### ISSUE TITLE
Sort Items By New Columns

### ISSUE THREAD

**Issue by DebugDax** [benjaminjonard/koillection#449]
Hello,

In relation to Issue #445 could you please allow the items in a collection to be sorted by those new columns being displayed?

Example: If we could sort this list by "Series Pack" which is an additional field from a template, instead of by "Name", it would make it much more useful to us. https://i.imgur.com/KZh1iDD.png

Thank you.

**Comment by benjaminjonard** [comment]
Hello, this should be implemented for the next release
