### ISSUE TITLE
"No results found" when clickin on a list

### ISSUE THREAD

**Issue by junpet** [benjaminjonard/koillection#456]
Version: 1.3.8 (in Docker)
DB: Postgres 14.4
Additional info: I've updated from v1.3.7.

Reproduction steps:
1. Create a list.
2. Create a template that uses the list created in the previous step.
3. Create a collection that uses the template created in the previous step as `Default template applied to items`
4. Try to add a new item to the collection created in the previous step. The data fields are loaded, but when you want to set the value for the list, it says `No results found` (see screenshot below).

I tried `Load collection fields` button, but the elements doesn't load. One solution is, to remove the field and select the template manually.

![image](https://user-images.githubusercontent.com/3465278/181688884-a9fd17e4-2bb9-4d93-b1fe-2111a541c3c2.png)

**Comment by benjaminjonard** [comment]
Hello, this should be fixed by release 1.3.9

**Comment by junpet** [comment]
Tested and working. Thank you for the fast fix.
