### ISSUE TITLE
adding tags

### ISSUE THREAD

**Issue by gitchris8** [benjaminjonard/koillection#462]
Hello, 
when adding a tag later, an error occurs:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by benjaminjonard** [comment]
Hello, I just published a release that should fix this issue (1.3.10)

**Comment by gitchris8** [comment]
Thank you for the quick fix
