### ISSUE TITLE
Load common fields

### ISSUE THREAD

**Issue by Izanagi52** [benjaminjonard/koillection#469]
What does "Load common fields" button on item creation form do ?

**Comment by FernandoLRubio** [comment]
It reloads the template fields. It seems like it is only populating whenever a field is missing. (If you manually deleted it, or if the template was modified)

**Comment by benjaminjonard** [comment]
Sorry for the late answer, the "load common fields" will add fields based on others items in the collections and prefill the value if possible.

For example if you have a collection of books and if all others books have an "Author" field, it will add an "Author" field. 
And if all "Author" fields have to the same value, it will also prefill the value.

**Comment by FernandoLRubio** [comment]
Is it based on the template or the other items in the collection?

**Comment by benjaminjonard** [comment]
On the other items in the collection
