### ISSUE TITLE
Error docker deploy

### ISSUE THREAD

**Issue by crishnakh** [benjaminjonard/koillection#478]
Hi, I'm trying to deploy the last version with docker but the koillection/koillection says is unhealthy and give me a 500 error on screen.
<img width="688" alt=" 2022-08-28 a las 14 49 53" src="https://user-images.githubusercontent.com/3185290/187074953-98de749e-3f22-465a-96fe-dbfe378478db.png">

**Comment by benjaminjonard** [comment]
Hello, is there any error logs when using this command ? `docker-compose logs koillection`

**Comment by crishnakh** [comment]
I only see a warning:
[28-Aug-2022 14:55:52] NOTICE: PHP message: PHP Warning:  Can't preload already declared class ReflectionEnum in /var/www/koillection/vendor/laminas/laminas-code/polyfill/ReflectionEnumPolyfill.php on line 8

On docker this:
% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (22) The requested URL returned error: 500 Internal Server Error

**Comment by crishnakh** [comment]
I think #479 have the same problem

**Comment by crishnakh** [comment]
Still having error 500

**Comment by benjaminjonard** [comment]
I'm looking into this, but can't really reproduce. 

I'm going to release a new version a bit later today that should at least fix the issue with logs being always empty. Hopefully we'll have more information about this issue

**Comment by crishnakh** [comment]
I'll try later to see if I can't give you something more. Thanks for trying

**Comment by crishnakh** [comment]
Hi @benjaminjonard thanks for everything! version 1.3.12 works good with docker
