### ISSUE TITLE
Koillection v1.3.11 on Docker with reverse proxy throws 404

### ISSUE THREAD

**Issue by junpet** [benjaminjonard/koillection#479]
I haven't changed in my `docker-compose.yml`. I've pulled the new image, started the container, the logs says the same as I can see on `v1.3.10`, but I can't reach koillection, I got 404. I waited several minutes, but I still got 404 with `v1.3.11`. Downgrading to `v1.3.10` and everything works.

**Comment by crishnakh** [comment]
Yes, I have downgrading to 1.3.10 and it's Ok

**Comment by junpet** [comment]
Thanks for the image update. The `v1.3.11` works again.
