### ISSUE TITLE
[Feature Request] Add Collection Worth and Collection Cost

### ISSUE THREAD

**Issue by Corza** [benjaminjonard/koillection#502]
I am tracking a collection that is worth more than is being spent on it. It would be great if each individual item could have how much it cost, and how much its worth and that could be totalled in the collection above. Then if there is multiple collections within one collection the entire value of the collection could be calculated and displayed as well as the cost.

**Comment by benjaminjonard** [comment]
Hello, this should be achievable since the last update (1.3.14)

I added a new type of field called Price. All Price fields with the same label in a collection will be added up and the result will be displayed on the collection (working with nested collections too)

**Comment by Corza** [comment]
Thank you, it works great.
