### ISSUE TITLE
Instructions for Migrating Data

### ISSUE THREAD

**Issue by DebugDax** [benjaminjonard/koillection#504]
Hello,

Can you please provide directions (or a Wiki article) on how to migrate data from one instance of Koillection to another?

I am transferring servers and need to move the SQL & Images. The Web front end provides tools to export the database and uploaded images, but there's no tools to import the SQL.

When running psql on the postgres image to try and import the *.sql, it states the database does not exist.

Could really use assistance and I think it would benefit others going forward if there was official documentation on how to do a transfer. Thank you!

**Comment by benjaminjonard** [comment]
Hello, 

If you are using docker, I guess the easiest way to migrate is just to move the volumes around. Copy them on the new server at the same path as your configured volumes in your docker-compose.yml, and that should be all.

In your case with pgsql command, the database needs to be created first with something like 

```
psql -U postgres
create database koillection;
exit
````
But I just found an error on the SQL export due to recent changes (it's missing quotes around some dates), I will publish a new version this week end to fix this.

**Comment by DebugDax** [comment]
Hi,

Thank you for the quick response and commits to resolve the issue, much appreciated!

I did try your advice and just move the postgresql volume from Server A to Server B, and it looks like it worked except there's some side effect:

it added "x2" to the end of every item: 
https://i.imgur.com/etGVIHi.png

the issue is that it can't be removed because when you edit the item that text is not present: 
https://i.imgur.com/CyqHIG3.png

even when adding new items that weren't imported they add with this "x2":
https://i.imgur.com/9kQdiug.png


All I did was make a backup of the volume from Server A, then copy and re-apply the same permissiosn to that folder on Server B.

Koillection Log:
https://pastebin.com/vK6iEbtH

postgresql Log:

> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 2022-09-10 14:50:19.614 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
> 2022-09-10 14:50:19.614 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> 2022-09-10 14:50:19.614 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> 2022-09-10 14:50:19.615 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> 2022-09-10 14:50:19.622 UTC [25] LOG:  database system was shut down at 2022-09-10 14:47:11 UTC
> 2022-09-10 14:50:19.629 UTC [1] LOG:  database system is ready to accept connections

**Comment by benjaminjonard** [comment]
I can reproduce on my own instance, that's seem to be a problem with the code, I will fix that as quickly as possible.

May I ask you which version of Koillection you are using ?

**Comment by DebugDax** [comment]
Sorry, I don't see where to see the Version numbers in the labels or Web front end, but here's the images they are using for Docker:

Server A (The Old Instance) is using:
koillection/koillection:beta@sha256:4bc42148de37669993486044a6ef296a997b30d701c1d03a532b7ee8bf0a1d68
(2022-08-04 10:15:43)

Server B (The New Instance) is using:
koillection/koillection:beta@sha256:c89f4aa0f41045a5d144fb2a693d76eccc0b64298ec4cd99c610644be7628e9c
2022-09-09 09:12:46

**Comment by benjaminjonard** [comment]
The last version of the beta image should fix this.

**Comment by DebugDax** [comment]
Hello,

I applied the newest beta image and the rows are correct now, I would consider this ticket resolved as I saw the commits where you fixed the SQL export. My original question was also solved by your information of just copying the volumes over directly for postgresql. Everything is running fine on the new server now!

Thank you again for all your help, fast work, and great software :)
